# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d60e697e628575e3c99b537aee87a65750a1822b6e4cc2755d7184f9e5fc73cce56cdd5ad0861831f3434f6ba7f100a2bd66ff2eaf9f2fcd45e2f3d172dcf04a

test:
  secret_key_base: 9e8de61c7132a869a1ff46bbb216ce2c4c4a10eacccccc30c729d9a724f4882b3fabee8dcd202f788fcd3010a695739b50aa17f931b97e6ea7de2bf1f7ef1931

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
